version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PUSHER_APP_ID: "${PUSHER_APP_ID}"
      PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      PUSHER_APP_SECRET: "${PUSHER_APP_SECRET}"
      PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
    volumes:
      - .:/app
