apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-chat-app-deployment
  labels:
    app: realtime-chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realtime-chat-app
  template:
    metadata:
      labels:
        app: realtime-chat-app
    spec:
      containers:
      - name: realtime-chat-app-container
        image: jaraxxx/wsl_test:final
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_PUSHER_APP_ID
          valueFrom:
            secretKeyRef:
              name: realtime-chat-app-secrets
              key: NEXT_PUBLIC_PUSHER_APP_ID
        - name: NEXT_PUBLIC_PUSHER_APP_KEY
          valueFrom:
            secretKeyRef:
              name: realtime-chat-app-secrets
              key: NEXT_PUBLIC_PUSHER_APP_KEY
        - name: NEXT_PUBLIC_PUSHER_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: realtime-chat-app-secrets
              key: NEXT_PUBLIC_PUSHER_APP_SECRET
        - name: NEXT_PUBLIC_PUSHER_APP_CLUSTER
          valueFrom:
            secretKeyRef:
              name: realtime-chat-app-secrets
              key: NEXT_PUBLIC_PUSHER_APP_CLUSTER
