apiVersion: v1
kind: Service
metadata:
  name: realtime-chat-app
spec:
  selector:
    app: realtime-chat-app
  ports:
    - protocol: TCP
      port: 80   # Use any port you want externally
      targetPort: 3000
      nodePort: 30000   # Define a NodePort
  type: NodePort   # Use NodePort service type
