apiVersion: v1
kind: Service
metadata:
  name: realtime-chat-app-service
spec:
  type: ClusterIP
  selector:
    app: realtime-chat-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
